In [1]:
import torch

In [2]:
import torch.nn.functional as F

In [3]:
F.sigmoid?

Signature: F.sigmoid(input)
Docstring:
sigmoid(input) -> Tensor

Applies the element-wise function :math:`\text{Sigmoid}(x) = \frac{1}{1 + \exp(-x)}`

See :class:`~torch.nn.Sigmoid` for more details.
File:      ~/.pyenv/versions/xcs224n/lib/python3.7/site-packages/torch/nn/functional.py
Type:      function


In [4]:
import torch.nn as nn

In [5]:
nn.Sigmoid?

Init signature: nn.Sigmoid()
Docstring:     
Applies the element-wise function:

.. math::
    \text{Sigmoid}(x) = \frac{1}{1 + \exp(-x)}


Shape:
    - Input: :math:`(N, *)` where `*` means, any number of additional
      dimensions
    - Output: :math:`(N, *)`, same shape as the input

.. image:: scripts/activation_images/Sigmoid.png

Examples::

    >>> m = nn.Sigmoid()
    >>> input = torch.randn(2)
    >>> output = m(input)
Init docstring: Initializes internal Module state, shared by both nn.Module and ScriptModule.
File:           ~/.pyenv/versions/xcs224n/lib/python3.7/site-packages/torch/nn/modules/activation.py
Type:           type
Subclasses:     


In [6]:
from IPython.display import Latex

$$ x_{proj} = ReLU(W_{\text{proj}}x_{\text{conv_out}} + b_{\text{proj}}) \in \mathbb{R}^{e_{\text{word}}}$$

$e_{word} = e_{char}\times m_{word}$

In [7]:
import numpy as np 
import torch

In [8]:
x = torch.randn(3, 5)
y = torch.randn(3, 5)

In [9]:
x

tensor([[-0.1355,  0.0165,  0.5267, -2.5321,  0.7066],
        [ 0.4018, -0.0481, -0.5418, -0.5878,  0.2209],
        [ 0.5097,  1.5385, -1.0192,  1.1768, -0.3335]])

In [10]:
y

tensor([[ 0.9137, -0.2251, -0.6497,  2.0474, -0.5563],
        [-0.2680,  0.2112, -1.0309,  0.4903, -0.4948],
        [-0.1052,  0.7104, -1.0319, -0.1977, -0.6747]])

In [11]:
kernel_size = 
nn.MaxPool1d()

SyntaxError: invalid syntax (<ipython-input-11-0d2b02846485>, line 1)

In [12]:
char_embed_size = 7
max_word_length = 10
kernel_size = 5

In [24]:
x = torch.randn(15, 7, 10)

In [16]:
x_conv = conv_layer(x)

In [17]:
x_conv.shape

torch.Size([15, 70, 6])

In [25]:
x_conv_relu = F.relu(x_conv)

In [26]:
x_conv_relu.shape

torch.Size([15, 70, 6])

In [27]:
m = nn.MaxPool1d(kernel_size=(max_word_length - kernel_size +1))

In [29]:
x_m = m(x_conv_relu)

In [30]:
x_m.shape

torch.Size([15, 70, 1])

In [36]:
x_m_2 = torch.max(x_m, dim=2)[0]

In [37]:
x_m_2.shape

torch.Size([15, 70])

In [1]:
class DummyVocab():
    def __init__(self):
        self.char2id = json.load(open('./sanity_check_en_es_data/char_vocab_sanity_check.json', 'r'))
        self.id2char = {v: k for k,v in self.char2id.items()}
        self.unk = self.char2id['<unk>']
        self.start_of_word = self.char2id['{']
        self.end_of_word = self.char2id['}']

In [2]:
import torch
import json
from nmt_model import NMT
from vocab import Vocab

In [14]:
sentence_length = 10
max_word_length = 21
batch_size = 5
embed_size = 3

vocab = Vocab.load('./sanity_check_en_es_data/vocab_sanity_check.json')

def test_model(sentence_length, batch_size, max_word_length, embed_size):
    model = NMT(embed_size=embed_size, hidden_size=3, dropout_rate=0.2, vocab=vocab)
    x = torch.zeros(sentence_length, batch_size, max_word_length,   dtype=torch.long)
    ME_source = model.model_embeddings_source
    output = ME_source.forward(x)
    output_expected_size = [sentence_length, batch_size, embed_size]

    assert list(output.size()) == output_expected_size, f'Output shape should be:\n{output_expected_size}, but is:\n{list(output.size())}'

print('-'*80)
print('Running Sanity Checks for Question 1f:  Model Embedding')

params = (10, 5, 21, 3)
test_model(*params)

#print('Testing batch size 1')
params = (10, 1, 21, 3)
test_model(*params)

#print('Testing max word length = sentence length')
params = (21, 5, 21, 3)
test_model(*params)

#print('Testing max word length = 20')
#params = (10, 5, 20, 3)
#test_model(*params)

#print('Testing embed_size=1')
params = (10, 5, 21, 1)
test_model(*params)
print('-'*80)
print('Sanity Checks Passed for Question 1f: Model Embedding!')

--------------------------------------------------------------------------------
Running Sanity Checks for Question 1f:  Model Embedding
--------------------------------------------------------------------------------
Sanity Checks Passed for Question 1f: Model Embedding!


In [27]:
x.size()

torch.Size([10, 5, 21])

In [28]:
ME_source

ModelEmbeddings(
  (char_embedding_layer): Embedding(96, 50, padding_idx=0)
  (cnn_layer): CNN(
    (conv_layer): Conv1d(50, 3, kernel_size=(5,), stride=(1,))
    (max_pool): MaxPool1d(kernel_size=17, stride=17, padding=0, dilation=1, ceil_mode=False)
  )
  (highway_layer): Highway(
    (projection_layer): Linear(in_features=3, out_features=3, bias=True)
    (gate_layer): Linear(in_features=3, out_features=3, bias=True)
    (dropout_layer): Dropout(p=0.3, inplace=False)
  )
)

In [29]:
output.size()

torch.Size([10, 5, 3])

In [30]:
output_expected_size

[10, 5, 3]

In [42]:
x[0, :, :]

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [43]:
output[0, :, :]

tensor([[0.1239, 0.0000, 0.0000],
        [0.1239, 0.0000, 0.1509],
        [0.0000, 0.0000, 0.0000],
        [0.1239, 0.0000, 0.1509],
        [0.0000, 0.0000, 0.0000]], grad_fn=<SliceBackward>)

In [2]:
from nmt_model import NMT
from char_decoder import CharDecoder
from vocab import Vocab

In [3]:
BATCH_SIZE = 5
EMBED_SIZE = 3
HIDDEN_SIZE = 3
DROPOUT_RATE = 0.0

In [25]:
sents = ["When I die, I want to die like my grandfather who died peacefully in his sleep.".split(), "Not screaming like all the passengers in his car.".split(),
"Always remember that you are absolutely unique.".split(), "Just like everyone else.".split(),
"If toast always lands butter-side down, and cats always land on their feet, what happens if you strap toast on the back of a cat and drop it?".split(),
"The road to success is always under construction.".split()]

In [57]:
from utils import pad_sents_char
import torch

In [27]:
data = []
for sent in sents:
    sent = ["<s>"] + sent + ["</s>"]
    data.append(sent)

In [62]:
lengths = [len(sent) for sent in sents]

In [70]:
sorted_sents = sorted(sents, key=lambda x: len(x), reverse=True)

In [71]:
lengths = [len(sent) for sent in sorted_sents]

In [73]:
from vocab import VocabEntry
vocab = VocabEntry(voc)
indices = vocab.words2charindices(sorted_sents)

padded = pad_sents_char(indices, char_pad_token=0)
sents_var = torch.tensor(padded, dtype=torch.long, device='cpu').permute(1,0,2)

In [31]:
from collections import Counter

In [41]:
chars = Counter("".join(["".join([w for w in sent]) for sent in sents]))

In [42]:
voc = dict()
voc["<pad>"] = 0
voc["{"] = 1
voc["}"] = 2
voc["<unk>"] = 3

In [44]:
for i, v in enumerate(chars.keys(), start=4):
    voc[i] = v

In [77]:
class DummyVocab():
    def __init__(self):
        self.char2id = voc
        self.id2char = {v: k for k, v in self.char2id.items()}
        self.char_unk = self.char2id['<unk>']
        self.start_of_word = self.char2id["{"]
        self.end_of_word = self.char2id["}"]

In [80]:
import json

vocab = DummyVocab()
#model = NMT(
#    embed_size=EMBED_SIZE,
#    hidden_size=HIDDEN_SIZE,
#    dropout_rate=DROPOUT_RATE,
#    vocab=vocab)
#
# char_vocab = vocab.tgt

decoder = CharDecoder(
    hidden_size=HIDDEN_SIZE,
    char_embedding_size=EMBED_SIZE,
    target_vocab=vocab)

In [96]:
sents_var[1:].contiguous().view(-1)

tensor([ 1, 49, 44,  ...,  0,  0,  0])

In [97]:
decoder

CharDecoder(
  (charDecoder): LSTM(3, 3)
  (char_output_projection): Linear(in_features=3, out_features=37, bias=True)
  (decoderCharEmb): Embedding(37, 3, padding_idx=0)
)

In [ ]:
python run.py train --train-src=./en_es_data/train_tiny.es --train-tgt=./en_es_data/train_tiny.en \
        --dev-src=./en_es_data/dev_tiny.es --dev-tgt=./en_es_data/dev_tiny.en --vocab=vocab_tiny_q2.json --batch-size=2 \
        --max-epoch=201 --valid-niter=100