In [2]:
from utils import pad_sents
from copy import deepcopy
import numpy as np

In [3]:
with open("en_es_data/train.es", "r") as f:
    spanish = [sent.strip("\n").split() for sent in f.readlines()]

In [4]:
toy_data = deepcopy(spanish[:50])

In [5]:
toy_data_pad = pad_sents(toy_data, "<PAD>")

In [13]:
%timeit maxlen = max(map(len, spanish))
%timeit maxlen = sorted(spanish, key=len)[0]
%timeit maxlen = np.argmax(np.array(list(map(len, spanish))))

8.04 ms ± 243 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
32.8 ms ± 786 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
17.3 ms ± 284 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [105]:
#slow but fun
def longest_idx_bool(sents, idx_only=True):
    maxlen = max(map(len, sents))
    len_list = list(map(lambda x: len(x) == maxlen, sents))
    if idx_only:
        return [i for i, _ in enumerate(len_list) if _ == True]
    return np.array(sents)[len_list]

In [101]:
%%timeit
longest_idx_bool(spanish)

40.3 ms ± 1.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
def longest_idx(sents, idx_only=True):
    maxlen = max(map(len, sents))
    if idx_only:
        return [i for i, sent in enumerate(sents) if len(sents[i]) == maxlen]
    return [sents[i] for i, sent in enumerate(sents) if len(sents[i]) == maxlen]

In [15]:
# REALLY slow
def longest_idx_slow(sents, idx_only=True):
    maxlen = sorted(sents, key=len)[0]
    if idx_only:
        return [i for i, sent in enumerate(sents) if len(sents[i]) == maxlen]
    return [sents[i] for i, sent in enumerate(sents) if len(sents[i]) == maxlen]

In [11]:
from more_itertools import locate
def longest_idx_locate(sents):
    maxlen = max(map(len, sents))
    filtered = list(locate(sents, lambda x: len(x) == maxlen))
    return filtered

In [19]:
%timeit longest_idx_slow(spanish)
%timeit longest_idx(spanish)
%timeit longest_idx_locate(spanish)

55.5 ms ± 2.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
28.4 ms ± 1.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
35.3 ms ± 2.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
def longest_idx_numpy(sents):
    maxlen = max(map(len, sents))
    nsents = np.where(lambda x: len(x) == maxlen, sents, None)
    return nsents
len(longest_idx_numpy(spanish)[0])

24

In [41]:
def pad_sents(sents, pad_token="<pad>"):
    longest_sent = max(map(len, sents))
    def pad_one(sent):
        sent.extend([pad_token]*(longest_sent-len(sent)))
        return sent
    sents_padded = list(map(pad_one, sents))
    return sents_padded

In [46]:
def pad_sents_2(sents, pad_token="<pad>"):
    longest_sent = max(map(len, sents))
    def pad_one(sent):
        sent.extend([pad_token]*(longest_sent-len(sent)))
        return sent
    sents_padded = [sent + [pad_token]*(longest_sent-len(sent)) for sent in sents]
    return sents_padded

In [ ]:
def pad_sents_3(sents, pad_token="<pad>"):
    longest_sent = max(map(len, sents))
    lengths = map(lambda x: longest_sent - x, sents)
    

In [47]:
%timeit pad_sents(spanish)
%timeit pad_sents_2(spanish)

157 ms ± 2.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
155 ms ± 1.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [115]:
# [(i, o) for i, o in zip(map(lambda x: 59-len(x), toy_data), toy_data)]
# def pad_sents_4(sents):
#     sent_map = map(len, sents)
#     maxlen = max(sent_map)
#     return [sent[1]+["<pad>"]*sent[0] for i, sent in enumerate(zip(map(lambda x: maxlen-x, sent_map), sents))]
#     
# 5*"<pad>".split()
# [sent[1]+sent[0]*"<pad>".split() for i, sent in enumerate(zip(map(lambda x: max(map(len, sents))-x, map(len, sents)), sents))]

In [127]:
import torch

In [142]:
x = torch.zeros(15, 8)
print(x.size())
print(x)
torch.split(x, 5)

torch.Size([15, 8])
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])


(tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]))

In [148]:
x = torch.zeros(2,1,2,1,2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
z = torch.squeeze(x, 0)
print(z.size())
a = torch.squeeze(x, 1)
print(a.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])
